# Whether to verify JWT
verify_jwt = false

# Allow all origins
allow_origins = ["*"]

# Allow all HTTP methods
allow_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]

# Allow all headers
allow_headers = ["*"]

# Import map
[import_map]
path = "import_map.json" 